apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: k8s-consumer-deployment
  labels:
    app: k8s-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-consumer
  template:
    metadata:
      labels:
        app: k8s-consumer
    spec:
      containers:
        - name: k8s-consumer
          image: greenpython/k8s-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: k8s-consumer-configmap
          startupProbe:
            httpGet:
              path: /probes/startup
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /probes/readiness
              port: 8080
            periodSeconds: 300
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /probes/liveness
              port: 8080
            periodSeconds: 60
            failureThreshold: 3