apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: k8s-consumer-service
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: k8s-consumer
  ports:
    - port: 8080
      targetPort: 8080