apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: k8s-producer-deployment
  labels:
    app: k8s-producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: k8s-producer
    spec:
      containers:
        - name: k8s-producer
          image: greenpython/k8s-producer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: app-properties.pod-name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: app-properties.namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: k8s-producer-configmap
            - secretRef:
                name: k8s-producer-secret
          startupProbe:
            httpGet:
              path: /probes/startup
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /probes/readiness
              port: 8080
            periodSeconds: 300
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /probes/liveness
              port: 8080
            periodSeconds: 60
            failureThreshold: 3
          resources:
            requests:
              cpu: "0.5"
              memory: "500Mi"
            limits:
              cpu: "1.0"
              memory: "1Gi"
      tolerations:
        - key: app
          value: m12
          operator: Equal
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64