apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: dev
spec:
  limits:
    - default:
        cpu: "0.3"
        memory: "300Mi"
      defaultRequest:
        cpu: "0.15"
        memory: "150Mi"
      max:
        cpu: "0.5"
        memory: "500Mi"
      min:
        cpu: "0.05"
        memory: "50Mi"
      type: Container