apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: dev
spec:
  limits:
    - default:
        cpu: "1.0"
        memory: "1Gi"
      defaultRequest:
        cpu: "0.5"
        memory: "500Mi"
      max:
        cpu: "1.2"
        memory: "2Gi"
      min:
        cpu: "0.1"
        memory: "260Mi"
      type: Container